// Code generated by Kitex v0.5.2. DO NOT EDIT.

package itemservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	mba "rpc-mba/kitex_gen/rpc/mba"
)

func serviceInfo() *kitex.ServiceInfo {
	return itemServiceServiceInfo
}

var itemServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "ItemService"
	handlerType := (*mba.ItemService)(nil)
	methods := map[string]kitex.MethodInfo{
		"GetItem": kitex.NewMethodInfo(getItemHandler, newItemServiceGetItemArgs, newItemServiceGetItemResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "mba",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.5.2",
		Extra:           extra,
	}
	return svcInfo
}

func getItemHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*mba.ItemServiceGetItemArgs)
	realResult := result.(*mba.ItemServiceGetItemResult)
	success, err := handler.(mba.ItemService).GetItem(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newItemServiceGetItemArgs() interface{} {
	return mba.NewItemServiceGetItemArgs()
}

func newItemServiceGetItemResult() interface{} {
	return mba.NewItemServiceGetItemResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetItem(ctx context.Context, req *mba.GetItemRequest) (r *mba.GetItemResponse, err error) {
	var _args mba.ItemServiceGetItemArgs
	_args.Req = req
	var _result mba.ItemServiceGetItemResult
	if err = p.c.Call(ctx, "GetItem", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
